export type Database = {
  public: {
    Tables: {
      leads: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          status_since: string | null;
          lead_status: string | null;
          contact_type: string | null;
          phone_status: string | null;
          appointment_date: string | null;
          appointment_time: string | null;
          offer_pv: boolean | null;
          offer_storage: boolean | null;
          offer_backup: boolean | null;
          tvp: boolean | null;
          documentation: string | null;
          doc_link: string | null;
          calendar_link: string | null;
          follow_up: boolean | null;
          follow_up_date: string | null;
          exported_to_sap: boolean | null;
          lat: number | null;
          lng: number | null;
          next_action: string | null;
          next_action_date: string | null;
          next_action_time: string | null;
          preliminary_offer: boolean | null;
          lost_reason: string | null;
          voicemail_left: boolean | null;
          phone_switched_off: boolean | null;
          not_reached_count: number | null;
          pv_kwp: number | null;
          storage_kwh: number | null;
          has_backup: boolean | null;
          has_ev_charger: boolean | null;
          has_heating_mgmt: boolean | null;
          quick_notes: string | null;
          tenant_id: string | null;
          user_id: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          status_since?: string | null;
          lead_status?: string | null;
          contact_type?: string | null;
          phone_status?: string | null;
          appointment_date?: string | null;
          appointment_time?: string | null;
          offer_pv?: boolean | null;
          offer_storage?: boolean | null;
          offer_backup?: boolean | null;
          tvp?: boolean | null;
          documentation?: string | null;
          doc_link?: string | null;
          calendar_link?: string | null;
          follow_up?: boolean | null;
          follow_up_date?: string | null;
          exported_to_sap?: boolean | null;
          lat?: number | null;
          lng?: number | null;
          next_action?: string | null;
          next_action_date?: string | null;
          next_action_time?: string | null;
          preliminary_offer?: boolean | null;
          lost_reason?: string | null;
          voicemail_left?: boolean | null;
          phone_switched_off?: boolean | null;
          not_reached_count?: number | null;
          pv_kwp?: number | null;
          storage_kwh?: number | null;
          has_backup?: boolean | null;
          has_ev_charger?: boolean | null;
          has_heating_mgmt?: boolean | null;
          quick_notes?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          status_since?: string | null;
          lead_status?: string | null;
          contact_type?: string | null;
          phone_status?: string | null;
          appointment_date?: string | null;
          appointment_time?: string | null;
          offer_pv?: boolean | null;
          offer_storage?: boolean | null;
          offer_backup?: boolean | null;
          tvp?: boolean | null;
          documentation?: string | null;
          doc_link?: string | null;
          calendar_link?: string | null;
          follow_up?: boolean | null;
          follow_up_date?: string | null;
          exported_to_sap?: boolean | null;
          lat?: number | null;
          lng?: number | null;
          next_action?: string | null;
          next_action_date?: string | null;
          next_action_time?: string | null;
          preliminary_offer?: boolean | null;
          lost_reason?: string | null;
          voicemail_left?: boolean | null;
          phone_switched_off?: boolean | null;
          not_reached_count?: number | null;
          pv_kwp?: number | null;
          storage_kwh?: number | null;
          has_backup?: boolean | null;
          has_ev_charger?: boolean | null;
          has_heating_mgmt?: boolean | null;
          quick_notes?: string | null;
          tenant_id?: string | null;
          user_id?: string | null;
        };
      };
    };
  };
};
